name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy project to EC2
        run: |
          rsync -avz --delete --exclude 'node_modules' ./backend ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/egg

      - name: Deploy on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/egg/backend
            docker build -t egg-library-api .
            docker stop egg-api || true
            docker rm egg-api || true
            docker run -d --name egg-api -p 7001:7001 egg-library-api
          EOF
